### ISSUE TITLE
Gulp build, dist folder still has all the TS files

### ISSUE THREAD

**Issue by mattiLeBlanc** [FountainJS/generator-fountain-webapp#95] opened 2016-08-01 00:50 UTC
Hi,

I use fountain for a Angular, Typescript, Stylus project with PUG. Have that all working fine with help from fellow gitters.

I was evaluating the build, and I noticed that the TS files are still present in my dist folder.
I assume these need to be removed before the files are copied over to the dist folder since all the TS files have already been converted to JS.
Am I correct?

**Comment by kuhnroyal** [comment] 2016-08-01 14:08
I changed a line in `gulp_tasks/misc.js`, added the `pug,ts`.

```
path.join(`!${conf.paths.src}`, '/**/*.{pug,ts,html,css,js,styl}')
```

**Comment by micaelmbagira** [comment] 2016-08-01 14:13
Duplicate of https://github.com/FountainJS/generator-fountain-angular2/issues/70 but I'll leave it open because not the same repo.

**Comment by mattiLeBlanc** [comment] 2016-08-01 22:32
@kuhnroyal Hi,

Yep, this works fine. Thanks

**Comment by micaelmbagira** [comment] 2016-08-02 07:03
I reopen it until next release 😉

**Comment by kuhnroyal** [comment] 2016-08-02 08:33
@mattiLeBlanc Since you use the pug-loader, you don't need the template-cache anymore. Try to remove all references to it.

**Comment by mattiLeBlanc** [comment] 2016-08-02 09:07
@kuhnroyal Is that related to issue https://github.com/FountainJS/generator-fountain-webapp/issues/97 ?

**Comment by kuhnroyal** [comment] 2016-08-02 09:54
No idea, I just know that you don't need it with pug-loader.

**Comment by micaelmbagira** [comment] 2016-08-19 09:14
Fixed in 0.7.0 (just released) 😉

**Closed as completed by micaelmbagira** 2016-08-19 09:14 UTC
Labels: fixed-in-next-release

**Comment by mattiLeBlanc** [comment] 2016-08-20 04:48
thanks guys! Great work.
