### ISSUE TITLE
gulp build error

### ISSUE THREAD

**Issue by tsogtbayar0821** [FountainJS/generator-fountain-webapp#93] opened 2016-07-29 13:55 UTC
in all versions using system js, get error when building.
here is error message i got
[16:48:19] 'systemjs' errored after 4.31 s
[16:48:19] Error on fetch for routes.js at file:///D:/wamp64/www/05Exercise/foun_angular_2/routes.js
        Loading .tmp\templates\index.js
        Error: ENOENT: no such file or directory, open 'D:\wamp64\www\05Exercise\foun_angular_2\routes.js'
    at Error (native)

**Comment by micaelmbagira** [comment] 2016-07-29 14:27
Duplicate of https://github.com/FountainJS/generator-fountain-webapp/issues/81

**Closed as completed by micaelmbagira** 2016-07-29 14:27 UTC
