### ISSUE TITLE
Typescript files are wrongly copied during the build process in the 'other' task

### ISSUE THREAD

**Issue by jordianguela** [FountainJS/generator-fountain-webapp#91] opened 2016-07-26 15:30 UTC
## Description

Using Angular1 and Typescript, when executing the build task it copies the .ts files to the /dist folder.

I've fixed it changing the 'other' task in the misc.js file:

``` js
function other() {
  const fileFilter = filter(file => file.stat.isFile());

  return gulp.src([
    path.join(conf.paths.src, '/**/*'),
    path.join(`!${conf.paths.src}`, '/**/*.{html,css,js,scss}')
  ])
    .pipe(fileFilter)
    .pipe(gulp.dest(conf.paths.dist));
}
```

**I think the .ts extesion should be excluded as well**
### Config

``` json
{
  "generator-fountain-angular1": {
    "version": "0.6.0",
    "props": {
      "framework": "angular1",
      "modules": "inject",
      "js": "typescript",
      "css": "scss",
      "resolved": "/usr/local/lib/node_modules/generator-fountain-webapp/node_modules/generator-fountain-angular1/generators/app/index.js",
      "namespace": "fountain-angular1",
      "argv": {
        "remain": [],
        "cooked": [],
        "original": []
      },
      "skip-cache": false,
      "skip-install": false,
      "sample": "techs",
      "router": "uirouter"
    }
  }
}
```

**Comment by micaelmbagira** [comment] 2016-07-26 15:31
Duplicate of https://github.com/FountainJS/generator-fountain-angular2/issues/70

**Closed as completed by micaelmbagira** 2016-07-26 15:31 UTC
