### ISSUE TITLE
gulp not cleared .tmp after a file change

### ISSUE THREAD

**Issue by gabrieldevelops** [FountainJS/generator-fountain-webapp#87] opened 2016-07-14 20:15 UTC
I realized that while the gulp is running in server mode, it does not perform cleaning the .tmp and the server is running on top of that folder files. 

I resolved this issue add 'clean' in task serve, in gulp file:
gulp.task('serve', gulp.series('clean','inject', 'watch', 'browsersync'));

any better suggestions?

**Comment by micaelmbagira** [comment] 2016-07-18 08:35
Hi @gabrieldevelops why do you need to clean the `.tmp` folder ?

**Comment by gabrieldevelops** [comment] 2016-07-18 20:14
@micaelmbagira  gulp serve use the .tmp files in browser, at least for me

**Comment by micaelmbagira** [comment] 2016-07-18 20:16
Alright, about this one, we have a fresh PR to fix the conflict that can occur when serving .tmp and src https://github.com/FountainJS/generator-fountain-browsersync/pull/21

**Comment by micaelmbagira** [comment] 2016-07-19 07:47
@gabrieldevelops Does it answer to your question ?

**Comment by gabrieldevelops** [comment] 2016-07-19 12:12
@micaelmbagira Yes, answer my question

**Comment by gabrieldevelops** [comment] 2016-07-19 12:13
I just need to update the generator?

**Comment by micaelmbagira** [comment] 2016-07-19 12:38
Nope, it's not published yet but what you have to do is reverse the order or `server.baseDir` in `conf/browsersync.conf.js`:

``` js
baseDir: [
  conf.paths.tmp,
  conf.paths.src
]
```

**Comment by gabrieldevelops** [comment] 2016-07-19 13:26
@micaelmbagira this is conf result in blank page, in Sources(F12 browser), not show app/src folder

**Comment by micaelmbagira** [comment] 2016-07-19 13:28
@gabrieldevelops I don't understand...

**Comment by gabrieldevelops** [comment] 2016-07-19 14:20
![gulp](https://cloud.githubusercontent.com/assets/19653723/16953278/d637d1c0-4da2-11e6-8ed2-be886524cf88.PNG)

**Comment by micaelmbagira** [comment] 2016-07-19 14:22
Can you send a github project so that I take a look ?

**Comment by gabrieldevelops** [comment] 2016-07-19 14:30
Yes, https://github.com/gabrieldevelops/acnt

**Comment by micaelmbagira** [comment] 2016-07-21 18:39
@gabrieldevelops I tried to replace `<div ui-view></div>` with `<div>hello</div>` in index.html and it works so the problem is more about your code.

**Comment by gabrieldevelops** [comment] 2016-07-21 19:38
@micaelmbagira after configure

baseDir: [
  conf.paths.src,
  conf.paths.tmp
]

the task inject not working, not inject files in index

**Comment by micaelmbagira** [comment] 2016-07-22 10:13
I don't know. I tested your project with `baseDir: [conf.paths.src, conf.paths.tmp]` and it works.

**Comment by dman777** [comment] 2016-08-31 05:55
**UPDATE**: The reverse order of `conf.paths.src` and `conf.paths.tmp` is not a fix. It creates a new breakage. In the order above, bower files do not get injected into the `index.html`. This definatelly should re-opened. 

I just instealled the latest stable fountain release tonight(Aug 31 `yo fountain-webap`) for angular and I hit this bug/issue also.  ~~I reversed the order which fixed this issue.~~

Maybe this issue should stay open untill the PR is merged and available in the latest release? 
I got lucky in finding this issue easiley, but it could make someone pull thier hair out if they are making removing files and not realizing they are still being injected.  

Also, maybe it would be a good idea to clear out the `.tmp` directory for every `gulp server` start? Tech. it shouldn't be needed, but maybe for good practice for anomalies like this. 

``` javascript
module.exports = function () {
  return {
    port: 9000,
    server: {
      baseDir: [
        conf.paths.src,
        conf.paths.tmp
      ],
      routes: {
        '/bower_components': 'bower_components'
      }
    },
    open: false
  };
};
```

**Comment by LuukMoret** [comment] 2016-08-31 06:35
I also had this issue and had to resolve this by changing the task 
`gulp.task('serve', gulp.series('inject', 'watch', 'browsersync'));` to 
`gulp.task('serve', gulp.series('clean', 'inject', 'watch', 'browsersync'));`

**Comment by dman777** [comment] 2016-08-31 06:46
:+1: Thanks, this did the trick. 

This is still major breakage because reversing order causes bower files not to be injected.

**Comment by micaelmbagira** [comment] 2016-08-31 06:49
@dman777 As you can see in this commit, the order of src and .tmp has been reversed only for **SystemJS** https://github.com/FountainJS/generator-fountain-browsersync/commit/de62a7e3abd9231fc1f5816f3a0a97dded930555.
When you generate a project with another option than SystemJS, for instance Bower or Webpack you have

```
server: {
      baseDir: [
        conf.paths.tmp,
        conf.paths.src
      ],
```

So the issue is different.

**Comment by dman777** [comment] 2016-08-31 06:53
@micaelmbagira Ok, thanks. I mis-understood. I thought the reverse fix was for non SystemJs since the issue also existed  for non SystemJs.

**Comment by micaelmbagira** [comment] 2016-08-31 06:55
If it still makes sense, you can open an issue regarding yours

**Comment by dman777** [comment] 2016-08-31 06:56
Could we re-open this one for convience? Since the title states the issue and all notes are on here? Simple fix, unless you wanted to code to handle/detect removing files dynamically.

**Comment by micaelmbagira** [comment] 2016-08-31 06:58
Ok, can you explain the exact bug you had then ?

**Comment by dman777** [comment] 2016-08-31 07:07
Sure.... 

when running `gulp serve` if I remove a file(s) in `src/app/` it will reside in the `.tmp/` and be injected into the app. Regardless of restarting `gulp serve`.

This will not be apparent to the developer. He/She will have side effects such as  code changes on existing .js sheets that will not take effect(being that the old .js files are still being injected and still taking effect). 

Restarting gulp with cleaning the `/.tmp` is a good fix. Although it will require restarting gulp if a file is removed. This has bitten me a few times in developing. 

Coding to detect a file removed real time and remove it in `./tmp` would be nice, but might be unwanted because of the extra code overhead and side effects that go with that.

**Comment by matheusdavidson** [comment] 2016-09-26 13:10
I'm also having the same problem. 

Usually when i create a new component/module/directive, i copy and paste an existing component/module/directive folder so i don't have to write everything again, just change names and code i need. 

Angular started complaining about component name colision and i couldn't understand why. After some debugging, i found that files remained as i copied in .tmp folder, they didn't change as i was editing.

To solve the problem, i have to manually delete the .tmp folder and restart the server.

**Comment by jensenkd** [comment] 2016-09-26 14:51
I'm having the same problem. .tmp not getting updated.

**Comment by zmts** [comment] 2016-09-30 09:20
Same problem. I fix it by adding 'clean' task in 'inject' task
`gulp.task('inject', gulp.series('clean', gulp.parallel('styles', 'scripts'), 'inject'));`
After any changes in js files .tmp folder is cleaning

**Comment by ozluy** [comment] 2016-11-24 20:11
+1 same issue!!! caching and does not recognize changes

**Comment by matheusdavidson** [comment] 2016-12-03 16:53
Guys, be careful with the solution above(@zmts, @LuukMoret, @gabrieldevelops), when you add ```clean``` task in the ```inject``` task you'll have problems when running ```npm run serve:dist``` or ```npm run build```:
```Error: File not found with singular glob: \www\myproject\.tmp\templateCacheHtml.js```

It happens because ```templateCache.js``` is generated in the ```partials``` task which is done before ```inject```, at this point ```clean``` will wipe out .tmp folder resulting in the error mentioned above.

If you run ```npm run serve``` it will be ok because no ```templateCache``` is generated.

**Comment by zmts** [comment] 2016-12-04 14:41
@matheusdavidson Before make build just remove `clean` task from `inject` and all be fine.

**Comment by matheusdavidson** [comment] 2016-12-04 23:57
did that @zmts, just wanted to document this here so people can find it if they get the same error.

**Closed as completed** 2016-12-12 20:26 UTC

**Comment by matheusdavidson** [comment] 2016-12-12 20:42
Is this fixed already? Updated and i still need to apply the fix.

**Comment by micaelmbagira** [comment] 2016-12-12 21:08
Won't fix. But you can add the `clean` task wherever you need in your gulp process @matheusdavidson
