### ISSUE TITLE
Can't make project with SystemJS (Angular 1 or Angular 2) to work

### ISSUE THREAD

**Issue by leonelgoncalves** [FountainJS/generator-fountain-webapp#41] opened 2016-05-27 02:10 UTC
I followed all the instructions and when i try to create a project with systemjs it doesnt work. 

First the installation throw this error:

<img width="1199" alt="screen shot 2016-05-26 at 9 09 18 pm" src="https://cloud.githubusercontent.com/assets/5423484/15595602/2e9c46ee-2386-11e6-8beb-d4efe39cc814.png">

I had to uninstall jspm and reinstall it to make it work. Then i run npm install and jspm install. And when i run gulp serve it throws this error:

<img width="1181" alt="screen shot 2016-05-26 at 9 07 50 pm" src="https://cloud.githubusercontent.com/assets/5423484/15595586/01e6c494-2386-11e6-853b-97cec7645687.png">

Webpacks projects runs just fine, but i can't manage to make a project with system/jspm to work.

Thanks in advance.

**Comment by zckrs** [comment] 2016-05-27 05:35
IMO duplicate of https://github.com/FountainJS/generator-fountain-systemjs/issues/34

Already fixed. Waiting to release

**Comment by leonel-torrealba** [comment] 2016-05-27 12:31
Well in that issue they only talk about the jspm. I said that you can change the version of jspm and the project will install. But I still have another problem after that (second picture) and when I run gulp serve it throws another error. So I don't think it's a duplicate

**Comment by zckrs** [comment] 2016-05-30 15:42
We have release a new version 0.5.1 who should fix your issue.

**Comment by leonel-torrealba** [comment] 2016-05-30 16:14
@zckrs thanks it is working now, thou i must say (and i know it's probably because you guys are still developing it) the Angular 1.X with SystemJS comes without any router. This is not a BIG issue but just saying hehe.

If this is not an issue just say it and close the issue.

**Comment by Swiip** [comment] 2016-05-31 06:56
We don't address router libs in Fountain yet (for any framework). It's planned for the future.

**Closed as completed by Swiip** 2016-05-31 06:56 UTC
