### ISSUE TITLE
gulp serve is no more working

### ISSUE THREAD

**Issue by matteocagno** [FountainJS/generator-fountain-webapp#151] opened 2016-10-21 08:35 UTC
By executing the classic intial command sequence
- yo fountain-webapp command
- npm install
- bower install

with the configuration attached
[.yo-rc.json.zip](https://github.com/FountainJS/generator-fountain-webapp/files/543865/default.yo-rc.json.zip)

executing "gulp serve" and then opening your browser on localhost:3000, the browser doesn't show anything and in its console an error 404 on index.css is reported.

Analyzing the situation, the server is serving the index.html from the [Project]\src folder instead of the .tmp folder.
Another situtation I found is that the .tmp folder is not directly containing any html file, but only an src folder containing all of them

**Comment by edgarmaia** [comment] 2016-10-21 12:46
@matteocagno see #150. It's same issue.

**Comment by end-user** [comment] 2016-11-16 14:33
Also waiting for the solution to this problem.

**Comment by micaelmbagira** [comment] 2016-12-12 20:55
Duplicate of https://github.com/FountainJS/generator-fountain-webapp/issues/150

**Closed as completed by micaelmbagira** 2016-12-12 20:55 UTC
